
server:
  port: 8080

  tomcat:
    uri-encoding: UTF-8
 
spring:
  datasource:
      name: miniprogram
      url: jdbc:mysql://127.0.0.1:3306/miniprogram?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver

#  ���ñ���
  messages:
    encoding: utf-8
  http:
    encoding:
      charset: UTF-8
  banner:
    charset: UTF-8

mybatis:
  #mapperLocationsָ��·����src/main/resources
  mapper-locations: mybatis/*.xml
#  mapper-locations: classpath: /mapper/*.xml  #ע�⣺һ��Ҫ��Ӧmapperӳ��xml�ļ�������·��
  type-aliases-package: per.niejun.entity  # ע�⣺��Ӧʵ�����·��
